### ISSUE TITLE
[Meetup] Monterrey

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Community-Team#197]
### Event Name:

Monterrey
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=7166455&action=edit

Found Meetup application for "Monterrey".

**Comment by peiraisotta** [comment]
asked for more info

**Comment by flopez1977** [comment]
It can be seen that days after the application, the Meetup has started with a new event that the applicant attended and it can be seen that the applicant is part of the Meetup organisation. 
It can be seen that the meetup had been inactive for almost a year until the applicant's contact. 
An email has been sent to the applicant stating that the application is closed for the time being and that if at a later date it is necessary to transfer the meetup because the current organisers are no longer with the meetup that this can be done.
