### ISSUE TITLE
[Meetup] Irun, Guipúzcoa, España

### ISSUE THREAD

**Issue by nukaga** [WordPress/Community-Team#333]
### Event Name:

Irun, Guipúzcoa, España
### Event Type:

Meetup
### Tracker URL:

https://central.wordcamp.org/wp-admin/post.php?post=8303934&action=edit

Found Meetup application for "Irun, Guipúzcoa, España".

**Comment by devinmaeztri** [comment]
Hello, @lumicliment! Thanks for vetting! Since the applicant is the previous organizer of the Irun group that we recently removed from the program as part of the reactivation project, I can ask Meetup.com to reinstate the group. We can add the link to the previous Irun tracker to the new application/tracker and add some context. You can also close this ticket. Thank you for your help!

**Comment by lumicliment** [comment]
Thanks @devinmaeztri!
